# Generated by Django 5.1.1 on 2024-09-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('incredients', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(default='', upload_to='restaurants\\zee_kitchen\\static\\images')),
                ('Extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.options')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
